### ISSUE TITLE
Invalid Syntax in gui.py

### ISSUE THREAD

**Issue by Lashway** [logston/olimex-ekg-emg#3]
System: Ubuntu 14.04, x86_64
Installation: Downloaded direct from git

Issue: gui won't execute
  -Tried with both Mock Data and leads

Error:

![screenshot_oferror](https://cloud.githubusercontent.com/assets/14006995/10932981/00e5caba-828a-11e5-8c6a-2ad5920f959b.png)

Offending Code:

![screenshot_syntaxerror](https://cloud.githubusercontent.com/assets/14006995/10932997/16c9e83e-828a-11e5-9580-25b90af1c049.png)

**Comment by Lashway** [comment]
Seems like this is actually a problem related to it downloading into the python2.7 directory rather than the python3.4.

May want to include instructions on how to avoid this for future users.

**Comment by logston** [comment]
Thanks @Lashway for the issue report! This is in fact a Python 2 vs Python 3 compatibility error. However, since I'm trying to push Python 3 (and I don't have time to make this package Python 2 compatible), this issue will not get fixed (at least not by me). I strongly encourage you to create a Python 3 virtual environment and try this code from within that environment. Thanks again for reaching out.

**Comment by Lashway** [comment]
Thanks for responding @logston .  I found a good tutorial on installing a Scientific Python Stack, but it's giving me trouble.  How is the software? Working well enough to be worth the slog?

**Comment by logston** [comment]
It looks like your running on a POSIX-ish system. Can you not create a virtual env and then pip install the core components (specified in the requirements.txt file) into that env? With pip 7.10 or greater, I would suspect that pip would download a wheel and installation would go smoothly. 

As for if my software is worth the slog, I'm quite biased but yes.
